import React from 'react';
import { X, FileSpreadsheet, Activity, Lightbulb, TrendingUp } from 'lucide-react';

export default function HowItWorksModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        <div className="p-6 border-b border-slate-800 flex items-center justify-between bg-slate-950/50">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-indigo-400" />
            How DecisionLens AI Works
          </h2>
          <button 
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto custom-scrollbar space-y-8">
          <p className="text-slate-300 text-sm leading-relaxed">
            DecisionLens AI strictly separates <strong className="text-white">deterministic math</strong> from <strong className="text-white">AI explanation</strong>. This ensures you get the power of LLMs without the risk of hallucinated business metrics.
          </p>

          <div className="grid gap-6">
            {/* Step 1 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                <FileSpreadsheet className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white mb-1">1. Upload & Verify Data</h3>
                <p className="text-sm text-slate-400">You upload a CSV. Our Python backend uses strictly deterministic Pandas & NumPy calculations to process the dataset, calculate KPIs, and generate verified insights.</p>
              </div>
            </div>

            {/* Step 2 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
                <Activity className="w-5 h-5 text-emerald-400" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white mb-1">2. Transparent Traceability</h3>
                <p className="text-sm text-slate-400">Every metric and insight shown on the dashboard is backed by traceable evidence. Nothing is generated by AI at this stage—it's pure mathematics.</p>
              </div>
            </div>

            {/* Step 3 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                <Lightbulb className="w-5 h-5 text-purple-400" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white mb-1">3. Grounded AI Explanation</h3>
                <p className="text-sm text-slate-400">When you ask a question, Google Gemini is provided only with the verified context. Gemini acts as an explanation engine, interpreting the verified math rather than inventing it.</p>
              </div>
            </div>

            {/* Step 4 */}
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
                <TrendingUp className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white mb-1">4. What-If Scenarios</h3>
                <p className="text-sm text-slate-400">Test business assumptions using the Simulator. This runs entirely on deterministic algebraic formulas, ensuring your projections remain accurate and predictable.</p>
              </div>
            </div>
          </div>
        </div>
        
        <div className="p-4 border-t border-slate-800 bg-slate-950/50 flex justify-end">
          <button 
            onClick={onClose}
            className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium rounded-lg transition-all shadow-lg shadow-indigo-900/20"
          >
            Got it
          </button>
        </div>
      </div>
    </div>
  );
}
